### ISSUE TITLE
Fix bug, clicking on one track in the list view plays a subsequent track

### ISSUE THREAD

**Issue by salieflewis** [public-assembly/neosound#42]
This bug has been hard to reproduce, but the play buttons next to each track don't seem to be consistently responsive, and they sometimes play a subsequent song.

https://user-images.githubusercontent.com/37086973/195717295-c0628fd4-1868-4f22-8e58-2938cc7d569b.mp4

**Comment by dblodorn** [comment]
@salieflewis this should be fixed now with this PR: #41

**Comment by dblodorn** [comment]
@salieflewis Also this:
https://github.com/public-assembly/curation-interactions/pull/25
bug stemmed from random order in neosound and inadequate handling of invalid entries (non editions contracts)

**Comment by salieflewis** [comment]
Gotcha @dblodorn 

Looks fixed to me! Closing this now.
